POST http://localhost:5000/api/auth/register
Content-Type: application/json


{
    "username": "trang123",
    "password": "123123"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json


{
    "username": "trang123",
    "password": "123123"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJkZTQ0ZjdlODZhNDRlMTg3NThlZTUiLCJpYXQiOjE2MjMwNTc0ODh9.s4bwm79ny-Iy4NdWTVxo_ATktzHiEF6qzZGU5oHy9SY

{
    "title": "Dạo 123",
    "description": "Chơi chơi Chơi chơi Chơi chơi Chơi chơi Chơi chơi Chơi chơi làdây là",
    "link": "Shopee.com",
    "status":"Học xong"
}


###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGJkZTQ0ZjdlODZhNDRlMTg3NThlZTUiLCJpYXQiOjE2MjMwNTc0ODh9.s4bwm79ny-Iy4NdWTVxo_ATktzHiEF6qzZGU5oHy9SY



